### ISSUE TITLE
@AndroidFindBy, @iOSFindBy doesn't work correctly with selenide

### ISSUE THREAD

**Issue by ProNationWolf** [codeborne/selenide-appium#11]
Hello ,
        My code Snippet , 

    @AndroidFindBy(id = "confirmNowButton")
    SelenideElement confirmBtn;

    public void clickConfirmBtn(){
          confirmBtn.shouldBe(Condition.visible).click();
    }

I am getting this error : 
org.openqa.selenium.InvalidSelectorException: Locator Strategy 'name' is not supported for this session (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds

I am calling the above method as - 

    @Test
    public void aSimpleInteraction() {

        LanguageCountrySelectionPage langPage = page(LanguageCountrySelectionPage.class);
        langPage.clickConfirmBtn();

    }

"selenide is trying to use name strategy instead."

Selenide version: 4.12.3
Appium Java client version: 6.1.0
Appium version : 1.7.2

Stack Trace :
```
Aug 17, 2018 4:20:27 PM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: OSS

org.openqa.selenium.InvalidSelectorException: Locator Strategy 'name' is not supported for this session (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'BLRL32864', ip: '172.22.197.75', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_25'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: D:\APK\1a\debug\app-1a-debu..., app-activity: com.amadeus.merci.app.ui.Ma..., app-package: com.amadeus.merci.app, appActivity: com.amadeus.merci.app.ui.La..., appPackage: com.amadeus.merci.app, appWaitActivity: com.amadeus.merci.app.ui.La..., appWaitPackage: com.amadeus.merci.app, autoWebview: false, autoWebviewTimeout: 4000, databaseEnabled: false, desired: {app: D:\APK\1a\debug\app-1a-debu..., app-activity: com.amadeus.merci.app.ui.Ma..., app-package: com.amadeus.merci.app, autoWebview: false, autoWebviewTimeout: 4000, deviceName: HTC, newCommandTimeout: 25, platformName: android, recreateChromeDriverSessions: true}, deviceManufacturer: LGE, deviceModel: LG-H930, deviceName: LGH930abcec1f7, deviceScreenSize: 1440x2880, deviceUDID: LGH930abcec1f7, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 25, platform: LINUX, platformName: Android, platformVersion: 7.1.2, recreateChromeDriverSessions: true, takesScreenshot: true, warnings: {}, webStorageEnabled: false}
Session ID: a75c7fde-fe8c-4c87-b2ce-57d3acb63958
*** Element info: {Using=name, value=confirmBtn}

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:317)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:62)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByName(RemoteWebDriver.java:395)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementByName(DefaultGenericMobileDriver.java:118)
	at io.appium.java_client.AppiumDriver.findElementByName(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElementByName(AndroidDriver.java:1)
	at org.openqa.selenium.By$ByName.findElement(By.java:284)
	at org.openqa.selenium.support.ByIdOrName.findElement(ByIdOrName.java:50)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:309)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:58)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at com.codeborne.selenide.impl.WebElementSelector.findElement(WebElementSelector.java:29)
	at com.codeborne.selenide.impl.ElementFinder.getWebElement(ElementFinder.java:56)
	at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:44)
	at com.codeborne.selenide.commands.Should.should(Should.java:35)
	at com.codeborne.selenide.commands.Should.execute(Should.java:29)
	at com.codeborne.selenide.commands.Should.execute(Should.java:12)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:144)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:90)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:65)
	at com.sun.proxy.$Proxy8.shouldBe(Unknown Source)
	at com.amadeus.Pages.LanguageCountrySelectionPage.clickConfirmBtn(LanguageCountrySelectionPage.java:37)
	at com.amadeus.sampleTestCases.Example.aSimpleInteraction(Example.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
```

**Comment by asolntsev** [comment]
@ProNationWolf The problem is that you use Selenide method `page`. Since it's built in Selenide, It doesn't support Appium. It only works with webdrivers like Chrome, Firefox etc.

You need to use method `com.codeborne.selenide.appium.ScreenObject#screen`.

```
LanguageCountrySelectionPage langPage = screen(new LanguageCountrySelectionPage());
```

I will update README and probably some other documentation with this information.

**Comment by ProNationWolf** [comment]
@asolntsev  Thank You.
