### ISSUE TITLE
ElementCollection or List of Elements , not working correctly with appium

### ISSUE THREAD

**Issue by ProNationWolf** [codeborne/selenide-appium#12]
Hello ,
My code snippet ,

    @AndroidFindBy(id = "field_selector_text")
    ElementsCollection countryLanguage;

    public void clickCountry(){
        countryLanguage.get(0).shouldBe(Condition.visible).click();
    }

Calling the above function as : 

        LanguageCountrySelectionPage langPage = screen(LanguageCountrySelectionPage.class);
        langPage.clickCountry();

I am getting the below error : 

Aug 21, 2018 10:36:12 AM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: OSS

java.lang.ClassCastException: io.appium.java_client.android.AndroidElement cannot be cast to com.codeborne.selenide.SelenideElement

	at com.amadeus.Pages.LanguageCountrySelectionPage.clickCountry(LanguageCountrySelectionPage.java:37)
	at com.amadeus.sampleTestCases.Example.aSimpleInteraction(Example.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

If i use the standard MobileElement (List) , the problem is not encountered.

I tried using 
  ((SelenideElement)countryLanguage.get(0)).shouldBe(Condition.visible).click();

I still faced the same issue. This problem occurs only when trying to access a List of Selenide Element.

**Comment by asolntsev** [comment]
Thank you for reporting the issue. I will investigate it.

**Comment by asolntsev** [comment]
@ProNationWolf Interesting, how can you get ClassCastException? I am trying code similar to yours, and getting only NullPointerException because `countryLanguage` is not initialised at all.

**Comment by asolntsev** [comment]
@ProNationWolf I guess I have fixes the issue (at least, my issue). Can you try the lastest master state (see commit https://github.com/codeborne/selenide-appium/commit/d53abb994bef2c877cd561321acb6605b0ee3607)?

**Comment by ProNationWolf** [comment]
Hello @asolntsev  , i used updated code from commit d53abb9 , and now the ElementCollection  is working as expected. Thank you.
