### ISSUE TITLE
Wrong error message if using annotations for elements

### ISSUE THREAD

**Issue by rosolko** [codeborne/selenide-appium#5]
Trying to search element using annotation with some invalid locator:
```java
public class Page extend BasePage {
    @AndroidFindBy(id = "search_button")
    private SelenideElement searchButton;
}
```
And trying to access element in test using getter:
```java
public class ClassWithTests {
    private final Page page = new Page();
    
    @Test
    public void someTest() {
        page.getSearchButton().click();
    }
}
```

Got an error:
```java
Element should be visible {NoSuchElementException: Can't locate an element by this strategy: Locator map:}
Element: 'NoSuchElementException: Can't locate an element by this strategy: Locator map:'
Screenshot: file:/.../build/reports/tests/1499844311539.1.png
Timeout: 4 s.
Caused by: NoSuchElementException: Can't locate an element by this strategy: Locator map:
    at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:66)
    at com.codeborne.selenide.commands.Should.should(Should.java:35)
    at com.codeborne.selenide.commands.Should.execute(Should.java:29)
    at com.codeborne.selenide.commands.Should.execute(Should.java:12)
    at com.codeborne.selenide.commands.Commands.execute(Commands.java:143)
    at ...
```

But some there ina a logs I can find need message:
```java
Caused by: org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: Locator map: 
- native content: "By.chained({By.id: formula1})" 
- html content: "by id or name "result"
```

**Comment by asolntsev** [comment]
@rosolko It seems to be a bug of Appium, not Selenide. Right?

**Comment by rosolko** [comment]
@asolntsev In my point of view - problem with annotation. I don't know, but selenide represent this find strategy as map, on his top level.

**Comment by amuthansakthivel** [comment]
@asolntsev - I think the error message is coming from selenium which means the context is web view. The user should use @FindBy to find elements in the web view instead of @AndroidFindBy

It is not an issue with appium or selenide-appium.

**Comment by asolntsev** [comment]
Agree. Thanks @amuthansakthivel !
By the way, we could improve error message in selenide-appium. We could detect that element is annotated by `@AndroidFindBy` or `@IOSFindBy`, but current webdriver is webview. And throw a clean error message.
