### ISSUE TITLE
Unable to intecart with elements via UIAutomator2 driver

### ISSUE THREAD

**Issue by rosolko** [codeborne/selenide-appium#7]
Set capability 
```java
desiredCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2);
```
instead of 
```java
desiredCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.APPIUM);
```
And run tests.
Got error:
```java
java.lang.ClassCastException: com.google.common.collect.Maps$TransformedEntriesMap cannot be cast to java.lang.String

	at org.openqa.selenium.remote.RemoteWebElement.getTagName(RemoteWebElement.java:122)
	at com.codeborne.selenide.commands.GetText.execute(GetText.java:14)
	at com.codeborne.selenide.commands.GetText.execute(GetText.java:8)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:143)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:87)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:63)
	at com.sun.proxy.$Proxy31.getText(Unknown Source)

```

**Comment by asolntsev** [comment]
@rosolko Is it really a bug of `selenide-appium`? Can we fix it?

**Comment by rosolko** [comment]
@asolntsev It looks like it is.
I'm trying to use just appium java library with and no problem.
I think the problem in selenide proxy. It had issues with uiautomator2 element proxy.

**Comment by rosolko** [comment]
@asolntsev I'm tying to call `toWebElement()` method for `SelenideElement` and cast web element to `MobileElement` before any actions and it work, but this way is kinda hack.

**Comment by rosolko** [comment]
Looks like this issue obsolete. So closed.
